### ISSUE TITLE
Failed to get tickets

### ISSUE THREAD

**Issue by mantsap89** [r723/flutter_helpcenter#3]
Hello, i am getting a "Failed to get tickets" error when calling ZendeskHelpcenter.showRequestList().
Please help.

Thank you in advance.

**Comment by mantsap89** [comment]
Any solution on this please?

**Comment by r723** [comment]
Because, You need to access correct jwt token, for more you can visit zendesk portal please

**Comment by mantsap89** [comment]
I have made the whole process. I created the POST endpoint that zendesk wants, in order to get the JWT token but i get the same message.

 Do you have any idea? It's very important for my app to use your plugin due to client needs.

Thank you in advance.
